[project]
name = "fau"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "opencv-python",
    "pillow",
    "deepface",
    "tf-keras"
]
requires-python = ">=3.9"
